---
- name: Check URL
  hosts: control
  vars:
    node: "sv"

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: "http://{{ node }}"